CREATE TABLE LU_DEPARTMENT (
	dept_no VARCHAR(4) NOT NULL,
	dept_name VARCHAR(30) NOT NULL,
	CONSTRAINT PK_DEPARTMENT PRIMARY KEY (dept_no, dept_name),
	CONSTRAINT UC_DEPARTMENT UNIQUE (dept_no)
);

CREATE TABLE LU_TITLE (
	title_id VARCHAR(5) NOT NULL,
	title VARCHAR(20) NOT NULL,
	CONSTRAINT PK_TITLE PRIMARY KEY (title_id, title),
	CONSTRAINT UC_TITLE UNIQUE (title_id)
);

CREATE TABLE EMPLOYEES (
	emp_no INT NOT NULL,
	emp_title_id VARCHAR(5) NOT NULL,
	birth_date DATE NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	sex VARCHAR(1),
	hire_date DATE,
	CONSTRAINT PK_EMPLOYEE_NUMBER PRIMARY KEY (emp_no),
	CONSTRAINT FK_EMPLOYEE_TITLE FOREIGN KEY (emp_title_id) REFERENCES LU_TITLE(title_id),
	CONSTRAINT UC_EMPLOYEE_NUMBER UNIQUE (emp_no)
);

CREATE TABLE SALARIES (
	emp_no INT,
	salary INT,
	CONSTRAINT FK_SALARY_EMPLOYEE_NUMBER FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no)
);

CREATE TABLE DEPT_MANAGER_MAP (
	dept_no VARCHAR(4),
	emp_no INT,
	CONSTRAINT FK_DEPARTMENT_NUMBER_MANAGER FOREIGN KEY (dept_no) REFERENCES LU_DEPARTMENT(dept_no),
	CONSTRAINT FK_EMPLOYEE_NUMBER_MANAGER FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no)
);

CREATE TABLE DEPT_EMPLOYEE_MAP (
	dept_no VARCHAR(4),
	emp_no INT,
	CONSTRAINT FK_DEPARTMENT_NUMBER_EMPLOYEE FOREIGN KEY (dept_no) REFERENCES LU_DEPARTMENT(dept_no),
	CONSTRAINT FK_EMPLOYEE_NUMBER FOREIGN KEY (emp_no) REFERENCES EMPLOYEES(emp_no)
);
